# Aim of this course is to develop sound reasoning and a scientific work flow that utilize optimization
## Knowledge centric eduction versus skill transfer centric eduction: 
## 1. Before the internet we were a knowledge constrained society e.g. everyone with a cellphone today has the same information at their fingertips than Pres Bill Clinton during his first term as President of the USA.
## 1.1 Education from the past was primarily knowledge transfer.
## 2. Essentially everyone today has access to information.
## 2.1 Education of today is primarily what we can do with the knowledge i.e. skill.
------------
# Not a course of only me explaining but purposefully constructed so that concepts are discovered. Why is this important?
## Stories that makes sense sticks, while arbitrary facts fade.
## Co-develop knowledge and skill. 
## Rather cover less material in class so that you can extend independently (Skill Transfer Model) as opposed to covering lots of material in class that you can't extend yourself afterwards (Knowledge Based Wikipedia Model). 
## Initial examples are on purpose chosen to be simplistic - often the answer is known before we start - this is important as it allows us to test what we do.
## Sometimes we do not know what the answer is - we can then first construct a simulated problem of which we know the answer.
## Why is this necessary or unnecessary?

This cell is a getting to know Jupyter-notebook cell - first change it to a Markdown cell before you type your reasons - make sure to share them in class.

------
# What is Optimization?
## Optimization solves problems, but not all problems, not yet anyway :)
# Consider yourself tackling a problem (assuming no optimization knowledge), four outcomes are plausible:
## 1. You don't know how to start and what to do - optimization won't help you here
## 2. You know exactly what to do and you find a single and unique solution to the problem - optimization won't help you here either, you are busy with an analysis problem
## 3. You know exactly what to do and find many, even an infinite number of solutions - optimization is your tool!
## 4. You know exactly what to do and you find no solution - optimization is your tool!

# Conceptual Highlight - Optimization is mathematical strategy to solve two types of problems:
## I. Problems that have many solutions (often infinite)
## II. Problems that have no solutions
# Conceptual Analogy - Basic Linear Algebra
## I. Analysis problems (only one solution exist e.g. solving using Gauss elimination)
## II. Underdetermined problems (infinite number of solutions exist)
## III. Overdetermined problems (no solution exist)
------
# Famous Quote: One should learn programming before statistics
# Obvious Quote: One should learn programming before *numerical methods*
# Fact: Optimization is an advanced numerical method
# Hindsight Obvious Quote: One should learn programming before optimization
------------
# Programming? Why should I learn to program, I am not an IT Person / Programmer - I am an Engineer, Scientist or Mathematician.
# For the same reason you are writing, although you are not Voltaire.
# Numerical literacy is a basic skill in 2018.
# Programming is the tool you use to become numerically literate.
----------
# What is programming? Programming is essentially the integration, arrangement and flow of data with operations that act on the data!
---------------------------------
# Before we recap these three Linear Algebra analogies let's consider basic Python calculations i.e. Python is my new calculator
# Numbers can be represented as different objects, namely integer, float and complex

----
## Integers: $MyIntegerCalculation = 1 + 2(3+4) + 5ˆ6$
### Press SHIFT + ENTER to run a cell

In [178]:
MyIntegerCalculation =  1 + 2*(3+4) + 5**6

In [44]:
print(MyIntegerCalculation)

15640


In [45]:
print(type(MyIntegerCalculation))

<class 'int'>


## Real/Float numbers: $MyIntegerCalculation = 1.0 + 2(3+4) + 5ˆ6$

In [5]:
MyRealCalculation = 1.0+ 2*(3+4) + 5**6
print(MyRealCalculation)
print(type(MyRealCalculation))

15640.0
<class 'float'>


## Complex numbers: $MyComplexCalculation = 1.0j + 2(3+4) + 5ˆ6$

In [183]:
MyComplexCalculation = 1.0j + 2*(3+4) + 5**6
print(MyComplexCalculation)
print(type(MyComplexCalculation))

(15639+1j)
<class 'complex'>


# Every thing in Python is an object!
## Object orientated programming is a fancy word for a basic concept!
## Basic concept: Strategy to keep your data (with specific type) and functions that operate on that data type in one place
## Compare the operations between integer and complex numbers?
## Put a dot at the end of the object name e.g. MyComplexCalculation. and press TAB

In [187]:
MyIntegerCalculation

15640

In [182]:
MyComplexCalculation.

SyntaxError: invalid syntax (<ipython-input-182-7bc8dae5d2f2>, line 1)

# How can we do more operations? Modules
## Modules are essentially objects that we can load into memory that contains lots of functions and data
## Numerical Python Modules - numpy
## Load the entire module into memory and give it a name mynumpy:
### Hash is the way we comment code out i.e. what follows after the hash will be ignored

In [4]:
import numpy as np

#help(np.fabs)
np.fabs?

# We can load specific functions or data from a module:
## fabs, cos and sin are functions
## pi is data
## from numpy import abs, cos, sin, pi

In [6]:
from numpy import fabs, cos, sin, pi
print(fabs)
print(pi)

<ufunc 'fabs'>
3.141592653589793


## Functions require data to operate on:
## e.g. sin(pi/2)
## Note the ( ) brackets are used to encapsulate the inputs into the function

In [8]:
print(sin(pi/4))

0.707106781187


------
# We can create our own functions: *def FUNCTION_NAME(INPUT1,INPUT2):*
## Below is a function that takes two inputs and computes $INPUT1^{INPUT2}$

In [12]:
def MyPower(Input1, Input2):
    return Input1**Input2
print(MyPower(2,3))
print(MyPower(9,0.5))

8
3.0


# Alternative: *MyPowerLambda = lambda INPUT1, INPUT2: INPUT1**INPUT2
## Lambda functions are quick but more limited than using def:

In [63]:
MyPowerLambda = lambda INPUT1,INPUT2: INPUT1**INPUT2
print(MyPowerLambda(2,3))
print(MyPowerLambda(9,0.5))

8
3.0


# Creating your own Module!
## Put your own functions into your own module
## Create a Python file: Navigator Window - Select New -> Text File
## Save the file as MyModule.py
## Place the MyPowerModule function into a python file MyModule.py
## *from MyModule import MyPowerModule*

In [64]:
from MyModule import MyPowerModule

print(MyPowerModule(2,3))
print(MyPowerModule(9,0.5))

8
3.0


In [1]:
import Nico as N

6


----
# We can do Linear Algebra: Vectors
## Two types are at our disposal to construct vectors:
## 1. List <[2,3,5]> - data type mainly developed for non-mathematical objects and no object support for mathematical operations.
## 2. NDArray < numpy.array([2,3,5])> - data type mainly developed for numbers and object support for element-wise (Hadamard) operations.
-------
## Consider the array $a = \left[2,3,5\right]$

In [39]:
aList = [2,3,5]
print('Object type : {}'.format(type(aList)))
print('a: {}'.format(aList))
print('2*a: {}'.format(2*aList))
print('a + a: {}'.format(aList+aList))
print('a*a: {}'.format(aList*aList))

Object type : <class 'list'>
a: [2, 3, 5]
2*a: [2, 3, 5, 2, 3, 5]
a + a: [2, 3, 5, 2, 3, 5]


TypeError: can't multiply sequence by non-int of type 'list'

In [36]:
import numpy as np
aArray = np.array([2,3,5])
print('Object type : {}'.format(type(aArray)))
print('a: {}'.format(aArray))
print('2*a: {}'.format(2*aArray))
print('a + a: {}'.format(aArray+aArray))
print('a*a: {}'.format(aArray*aArray))

Object type : <class 'numpy.ndarray'>
a: [2 3 5]
2*a: [ 4  6 10]
a + a: [ 4  6 10]
a*a: [ 4  9 25]


# Linear Algebra operations are available from functions in modules
## numpy module has support for numerous Linear Algebra operations that operate on both  Lists and NDarrays 

In [42]:
import numpy as np
aArray = np.array([2,3,5])
print('Object type : {}'.format(type(aArray)))
print('Cross product a x a: {}'.format(np.cross(aArray,aArray)))
print('Inner (dot) product aˆTa: {}'.format(np.dot(aArray,aArray)))
print('Outer product aaˆT:\n {}'.format(np.outer(aArray,aArray)))

Object type : <class 'numpy.ndarray'>
Cross product a x a: [0 0 0]
Inner (dot) product aˆTa: 38
Outer product aaˆT:
 [[ 4  6 10]
 [ 6  9 15]
 [10 15 25]]


-------
# We can do Linear Algebra: Matrices
## Two data types are at our disposal
## 1. List <[[2,3,5],[7,11,13],[17,19,23]]> - data type mainly developed for non-mathematical objects and no object support for mathematical operations
## 2. NDarray < numpy.array([[2,3,5],[7,11,13],[17,19,23]])> - data type mainly developed for numbers and object support for element-wise (Hadamard) operations.
-------
## Consider the matrix $M = \left[\begin{eqnarray}
2&&3&&5\\
7&&11&&13\\
17&&19&&23\\
\end{eqnarray}\right]$

# Linear Algebra operations need to be specified explicitely
## numpy module has support for numerous Algebra operations and works on both Lists and NDarrays

In [6]:
import numpy as np
aList = [2,3,5]
MList = [[2,3,5],[7,11,13],[17,19,23]]

aArray = np.array([2,3,5])
MArray = np.array([[2,3,5],[7,11,13],[17,19,23]])

print('a : {}'.format(aList))
print('M : {}'.format(MList))
print('aArray : {}'.format(aArray))
print('MArray :\n {}'.format(MArray))


print('----------------------------------------------------------------')
Ma = np.dot(MList,aList)
print('Matrix vector product M a = : {}'.format(np.dot(MList,aList)))
print('vector Matrix vector product a^T M a = : {}'.format(np.dot(aList,Ma)))
print('----------------------------------------------------------------')
x = np.linalg.solve(MList,aList)
print('Solving Linear System Mx = a: {}'.format(x))
print('Test solution x -> Mx = a: {}'.format(np.dot(MList,x) - aList))
print('----------------------------------------------------------------')
EigVal,EigVec = np.linalg.eig(MList)
print('Eigenvalues of M: {}'.format(EigVal))
print('Eigenvectors of M:\n {}'.format(EigVec))
print('----------------------------------------------------------------')
L1 = EigVal[0]
v1 = EigVec[:,0]
M_L1I = np.array(MList) - L1*np.eye(3)
print('Check First Eigenvector Solution:  (M  - L1 I)v1 = 0:\n {}'.format(np.dot(M_L1I,v1)))
print('----------------------------------------------------------------')
print('First Eigenvalue:  L1:\n {}'.format(EigVal[0]))
v1Mv1 = np.dot(v1,np.dot(MList,v1))
print('Compute First Eigenvalue from Eigenvector:  v1ˆT M v1:\n {}'.format(v1Mv1))

a : [2, 3, 5]
M : [[2, 3, 5], [7, 11, 13], [17, 19, 23]]
aArray : [2 3 5]
MArray :
 [[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]
----------------------------------------------------------------
Matrix vector product M a = : [ 38 112 206]
vector Matrix vector product a^T M a = : 1442
----------------------------------------------------------------
Solving Linear System Mx = a: [-0.12820513 -0.61538462  0.82051282]
Test solution x -> Mx = a: [ -2.22044605e-16  -8.88178420e-16  -1.77635684e-15]
----------------------------------------------------------------
Eigenvalues of M: [ 36.81172799  -1.91702763   1.10529963]
Eigenvectors of M:
 [[-0.16510917 -0.60574007  0.36952037]
 [-0.4789958  -0.3769456  -0.8244886 ]
 [-0.86214963  0.70070748  0.42857116]]
----------------------------------------------------------------
Check First Eigenvector Solution:  (M  - L1 I)v1 = 0:
 [ -3.33066907e-15  -5.32907052e-15  -7.10542736e-15]
----------------------------------------------------------------
First Eigen

-------------
# Accessing Vector and Matrix entries: Use [ ] brackets
## Specify index number - indexes start at 0

In [107]:
MArray = np.array(MList)
print('M is :\n {}'.format(MArray))
print('Entry in Second row, third column: {}'.format(MArray[1,2]))

M is :
 [[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]
Entry in Second row, third column: 13


# Extracting a row or column: Use : to indicate all row or column entries

In [110]:
print('M is :\n {}'.format(MArray))
print('Third row: {}'.format(MArray[2,:]))
print('First column: {}'.format(MArray[:,0]))

M is :
 [[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]
Third row: [17 19 23]
First column: [ 2  7 17]


# Extracting a sub-matrix: Use BEGIN:END to indicate row or column range
# END index is not included in sub-matrix i.e. always specify 1 larger than matrix that you want to extract

In [8]:
print('M is :\n {}'.format(MArray))
print('Extract 2x2 matrix from row 2-3 and column 1-2:\n {}'.format(MArray[1:3,0:2]))

M is :
 [[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]
Extract 2x2 matrix from row 2-3 and column 1-2:
 [[ 7 11]]


# Indicating index from the end: Use -NUMBER
# Indication up to the end: Use NUMBER:

In [116]:
print('M is :\n {}'.format(MArray))
print('Extract 2x3 vector from row 2 to the end and column 1 to the second last column:\n {}'.format(MArray[1:,0:-1]))

M is :
 [[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]
Extract 2x3 vector from row 2 to the end and column 1 to the second last column:
 [[ 7 11]
 [17 19]]


-------
# Reading and Interpreting Error Messages
## SyntaxError: Mistake with syntax e.g. bracket not closing
## TypeError: operation that is not permitted or defined for data type
## IndexError: Accessing an index that is out of bounds or not permitted
## ZeroDivisionError: Dividng by zero
## NameError: Using an undefind name
## ValueError: The object has the right type but the operation is on the value is not permitted
## AttributeError: Accessing an atribute of an object that does not exist
## LinAlgError: Inconsistent Linear Algebra Operations
## Spot and correct the following mistakes

In [127]:
a = (((45 + 6)*3 - 3)/76

SyntaxError: unexpected EOF while parsing (<ipython-input-127-a9ad4b73ef9b>, line 1)

In [126]:
b = MList*aList
print(b)

TypeError: can't multiply sequence by non-int of type 'list'

In [129]:
print(MList[2][3])

IndexError: list index out of range

In [130]:
print(MArray*aArray - bArray)

NameError: name 'bArray' is not defined

In [132]:
print(int('45'))
print(int('PMO'))

45


ValueError: invalid literal for int() with base 10: 'PMO'

In [133]:
print(int('45')/int('0'))

ZeroDivisionError: division by zero

-------
# Revisiting the three Linear Algebra Analogies
------
# Consider the following linear system of equations:
## Analysis of Linear Algebra system of equations
## $\mathbf{A}\mathbf{x} = \mathbf{b}$
## $$\mathbf{A} = 
\left[\begin{eqnarray}
&5 && 2 && 1 && 0 \\
&0 && 5 && 3 && 1 \\
&5 && 2 && 4 && 1 \\
&5 && 0 && 0 && 7 \\
\end{eqnarray}\right]
$$
$$
\mathbf{b}=
\left[\begin{eqnarray} 
&1&\\
&2&\\
&3&\\
&4&\\ 
\end{eqnarray}\right]
$$

In [136]:
import numpy as np
A = np.array([[5,2,1,0],[0,5,3,1],[5,2,4,1],[5,0,0,7]])
b = np.array([1,2,3,4])
print('Enter your code to solve the system of equations')
print('Enter your code to test that your answer is correct')

Enter your code to solve the system of equations
Enter your code to test that your answer is correct


-------
# Consider the following linear system of equations:
## Overdetermined system of Linear Algebra equations
## $\mathbf{A}\mathbf{x} = \mathbf{b}$
## $$\mathbf{A} = 
\left[\begin{eqnarray}
&5 && 2 && 1 && 0 \\
&0 && 5 && 3 && 1 \\
&5 && 2 && 4 && 1 \\
&5 && 0 && 0 && 7 \\
&0 && 3 && 0 && 2 \\
\end{eqnarray}\right]
$$
$$
\mathbf{b}=
\left[\begin{eqnarray} 
&1&\\
&2&\\
&3&\\
&4&\\ 
&9&\\ 
\end{eqnarray}\right]
$$

In [141]:
import numpy as np
A = np.array([[5,2,1,0],[0,5,3,1],[5,2,4,1],[5,0,0,7],[0,3,0,2]])
b = np.array([1,2,3,4,9])
x = np.linalg.solve(A,b)

LinAlgError: Last 2 dimensions of the array must be square

## Overdetermined system of Linear Algebra equations
## $\mathbf{A}\mathbf{x} = \mathbf{b}$
## We cannot solve the system as no solutions exist
## Not all approximate solutions are equivalent i.e. 
## choosing $\mathbf{x}$ such that $\mathbf{A}\mathbf{x} - \mathbf{b}\approx \mathbf{0}$ is not a bad idea.
## For example if the $L2-$norm of the difference is as small as possible i.e. Find $\mathbf{x}$ such that $f(\mathbf{x}) = \|\mathbf{A}\mathbf{x} - \mathbf{b}\|_2$ is a minimum, or formally
## $$
\min_{\mathbf{x}} f(\mathbf{x})\\
\min_{\mathbf{x}} \|\mathbf{A}\mathbf{x} - \mathbf{b}\|_2
$$
## Two approaches to solve this
## 1. Direct minimization of the error using scipy.optimize
## 2. Optimality criterion i.e. compute gradient of the objective function and set it equal to $\mathbf{0}$
-----
# 1. Direct minimization of the error using scipy.optimize
## Step 1: Formulate a function $f(\mathbf{x})$
## Step 2: Choose initial guess for solution $\mathbf{x}_0$
## Step 3: Find the minimum to the problem $\mathbf{x}_0$

In [146]:
import scipy.optimize as opt
import numpy as np
A = np.array([[5,2,1,0],[0,5,3,1],[5,2,4,1],[5,0,0,7],[0,3,0,2]])
b = np.array([1,2,3,4,9])

def MyObjective(x):
    return np.linalg.norm(np.dot(A,x)-b)

x0 = np.array([1,2,3,4])
result = opt.minimize(MyObjective,x0)
print(result)
print(type(result))

      fun: 5.548765995358565
 hess_inv: array([[ 0.21213718,  0.09724088, -0.26310847, -0.14083711],
       [ 0.09724088,  0.37305717, -0.421634  , -0.10237144],
       [-0.26310847, -0.421634  ,  0.83333885,  0.174866  ],
       [-0.14083711, -0.10237144,  0.174866  ,  0.20960889]])
      jac: array([ -4.17232513e-07,  -8.34465027e-07,  -3.57627869e-07,
        -6.55651093e-07])
  message: 'Optimization terminated successfully.'
     nfev: 96
      nit: 13
     njev: 16
   status: 0
  success: True
        x: array([ 0.10776081,  1.28753167, -0.78435108,  0.64440199])
<class 'scipy.optimize.optimize.OptimizeResult'>


## The result is of class 'scipy.optimize.optimize.OptimizeResult'
## Specifically, it is a dictionary
## A dictionary is a way to keep different objects togehther by giving each object a label instead of an index number
## result['x'] would give obtained the solution

In [148]:
print(result['x'])
print(type(result['x']))

[ 0.10776081  1.28753167 -0.78435108  0.64440199]
<class 'numpy.ndarray'>


# 2. Optimality criterion
## Step 1: Compute gradient of $f(\mathbf{x})$
## Step 2: Solve for the gradient equal to $0$
## Rewrite into equivalent objective i.e. $\|\mathbf{A}\mathbf{x} - \mathbf{b}\|_2 = \left((\mathbf{A}\mathbf{x} - \mathbf{b})^\textrm{T}(\mathbf{A}\mathbf{x} - \mathbf{b})\right)^{0.5}$ is equivalent in terms of optimization solution than $\tilde{f}(\mathbf{x})=(f(\mathbf{x}))^2$
## $\tilde{f}(\mathbf{x}) = \left((\mathbf{A}\mathbf{x} - \mathbf{b})^\textrm{T}(\mathbf{A}\mathbf{x} - \mathbf{b})\right) = \mathbf{x}^\textrm{T}\mathbf{A}^\textrm{T}\mathbf{A}\mathbf{x} - 2\mathbf{x}^\textrm{T}\mathbf{A}^\textrm{T}\mathbf{b} + \mathbf{b}^\textrm{T}\mathbf{b}$
## Step 1: $\nabla \tilde{f}(\mathbf{x}) = 2\mathbf{A}^\textrm{T}\mathbf{A}\mathbf{x} - 2\mathbf{A}^\textrm{T}\mathbf{b}$
## Step 2: Solve for $\nabla \tilde{f}(\mathbf{x}) = 2\mathbf{A}^\textrm{T}\mathbf{A}\mathbf{x} - 2\mathbf{A}^\textrm{T}\mathbf{b} = \mathbf{0}$ i.e.
## Solve for the linear system
## $$
\mathbf{A}^\textrm{T}\mathbf{A}\mathbf{x} = \mathbf{A}^\textrm{T}\mathbf{b}
$$

In [151]:
import numpy as np
A = np.array([[5,2,1,0],[0,5,3,1],[5,2,4,1],[5,0,0,7],[0,3,0,2]])
b = np.array([1,2,3,4,9])

ATA = np.dot(A.transpose(),A)
ATb = np.dot(A.transpose(),b)
x = np.linalg.solve(ATA,ATb)
print(x)
print('Compare solution to answer from direct minimization')

[ 0.10776081  1.28753181 -0.78435115  0.64440204]
Compare solution to answer from direct minimization


## Underdetermined system of Linear Algebra equations
## $\mathbf{A}\mathbf{x} = \mathbf{b}$
## $$\mathbf{A} = 
\left[\begin{eqnarray}
&5 && 2 && 1 && 0 \\
&0 && 5 && 3 && 1 \\
&5 && 2 && 4 && 1 \\
\end{eqnarray}\right]
$$
$$
\mathbf{b}=
\left[\begin{eqnarray} 
&1&\\
&2&\\
&3&\\
\end{eqnarray}\right]
$$

In [152]:
import numpy as np
A = np.array([[5,2,1,0],[0,5,3,1],[5,2,4,1]])
b = np.array([1,2,3])
x = np.linalg.solve(A,b)

np.linalg.n

LinAlgError: Last 2 dimensions of the array must be square

## We cannot easily solve the system as an infinite number of solutions exist
## Additional constraints or criteria can reduce the problem to a unique solution
## Many constraints or criteria are possible, this is called regularizing the problem
## Let's choose the answer such that the $\mathbf{x}$ has the shortest length i.e.
## Shortest length of $\mathbf{x}$ can be expressed as $\min_{\mathbf{x}}\|\mathbf{x}\|_2^2$ 
## Find $\mathbf{x}$ such that $f(\mathbf{x}) = \|\mathbf{x}\|_2^2$ is a minimum subject to
## $\mathbf{A}\mathbf{x} = \mathbf{b}$, or formally
## $$
\min_{\mathbf{x}} \|\mathbf{x}\|_2^2\\
\textrm{s.t.}\\
\mathbf{A}\mathbf{x} = \mathbf{b}
$$
## Two approaches to solve this
## 1. Direct minimization of the error using scipy.optimize
## 2. Optimality criterion i.e. compute gradient of the objective function and set it equal to $\mathbf{0}$
-----
# 1. Direct minimization of the error using scipy.optimize
## Step 1: Formulate a function $f(\mathbf{x})$ and constraint function $g(\mathbf{x})$
## Step 2: Choose initial guess for solution $\mathbf{x}_0$
## Step 3: Find the minimum to the problem $\mathbf{x}_0$

In [162]:
import scipy.optimize as opt
import numpy as np
A = np.array([[5,2,1,0],[0,5,3,1],[5,2,4,1]])
b = np.array([1,2,3])

def MyObjective(x):
    return np.linalg.norm(x)

def MyConstraint(x):
    return np.dot(A,x)-b


x0 = np.array([1,2,3,4])
result = opt.minimize(MyObjective,x0,constraints=[{'type':'eq','fun':MyConstraint}])
print(result)
print(type(result))

     fun: 0.6374750991205776
     jac: array([  1.24995388e-01,   7.45058060e-09,   9.43711847e-01,
         3.06241907e-01])
 message: 'Optimization terminated successfully.'
    nfev: 32
     nit: 5
    njev: 5
  status: 0
 success: True
       x: array([  7.96814390e-02,  -1.55381166e-18,   6.01592805e-01,
         1.95221585e-01])
<class 'scipy.optimize.optimize.OptimizeResult'>


In [165]:
print('Check constraint violation {}'.format(MyConstraint(result['x'])))

Check constraint violation [  2.22044605e-16   0.00000000e+00   0.00000000e+00]


# 2. Optimality criterion
## Step 1: Introduce a new variable per constraint
## Step 2: Construct the Lagrangian (we will cover the ideas behind it a bit later)
## Step 3: Compute the gradient of the Lagrangian
## Step 4: Solve for the gradient equal to $\mathbf{0}$
-------
## The Lagrangian is $\mathbf{x}^\textrm{T}\mathbf{x} + \left(\mathbf{b}^\textrm{T} - \mathbf{x}^\textrm{T}\mathbf{A}^\textrm{T} \right)\mathbf{\lambda}^\textrm{T}$
## The gradient w.r.t. $\mathbf{x}$ and $\mathbf{\lambda}$ is
## $$
\nabla L(\mathbf{x},\mathbf{\lambda}) = 
\left[
\begin{eqnarray} 
2\mathbf{x} - \mathbf{A}^\textrm{T}\mathbf{\lambda}^\textrm{T} \\
\mathbf{b} - \mathbf{A}\mathbf{x}\\
\end{eqnarray}
\right]$$
## Set gradient equal to $\mathbf{0}$
## $$
\left[
\begin{eqnarray} 
2\mathbf{x} - \mathbf{A}^\textrm{T}\mathbf{\lambda}^\textrm{T} = \mathbf{0} \\
\mathbf{A}\mathbf{x} - \mathbf{b} = \mathbf{0}
\end{eqnarray}
\right]$$
## $$
\left[
\begin{eqnarray} 
\mathbf{x} = \frac{1}{2}\mathbf{A}^\textrm{T}\mathbf{\lambda}^\textrm{T}\\
\mathbf{A}\mathbf{x} = \mathbf{b}
\end{eqnarray}
\right]$$
## $$
\frac{1}{2}\mathbf{A}\mathbf{A}^\textrm{T}\mathbf{\lambda}^\textrm{T} = \mathbf{b}
$$
## Solving for $\mathbf{\lambda}^\textrm{T}$
##  $$
\mathbf{\lambda}^\textrm{T} = 2\left(\mathbf{A}\mathbf{A}^\textrm{T}\right)^{-1}\mathbf{b}
$$
## with substitution back into $\mathbf{x} = \frac{1}{2}\mathbf{A}^\textrm{T}\mathbf{\lambda}^\textrm{T}$ which gives the solution
## $$
\mathbf{x} = \mathbf{A}^\textrm{T}\left(\mathbf{A}\mathbf{A}^\textrm{T}\right)^{-1}\mathbf{b}
$$
------------
## Hence, we first solve for the linear system
## $$
\frac{1}{2}\mathbf{A}\mathbf{A}^\textrm{T}\mathbf{\lambda}^\textrm{T} = \mathbf{b}
$$
## and then compute
## $$
\mathbf{x} = \frac{1}{2}\mathbf{A}^\textrm{T}\mathbf{\lambda}^\textrm{T}
$$

In [171]:
import numpy as np
A = np.array([[5,2,1,0],[0,5,3,1],[5,2,4,1]])
b = np.array([1,2,3])

AAT = np.dot(A,A.transpose())
LT = np.linalg.solve(0.5*AAT,b)
x = np.dot(0.5*A.transpose(),LT)
print(x)
print('Compare solution to answer from direct minimization')
print('Test solution: {}'.format(np.dot(A,x)-b))

[  7.96812749e-02   5.55111512e-17   6.01593625e-01   1.95219124e-01]
Compare solution to answer from direct minimization
Test solution: [ -3.33066907e-16   0.00000000e+00  -4.44089210e-16]


-------
# We have already optimized our first problems but still don't quite know what optimization is all about.
# Tomorrow we explore what optimization is, and fully understand why we made the choices we made in solving the underdetermined and overdetermined system of equations
------

# Additional Problems
## Consider the matrix $$\mathbf{A} = 
\left[\begin{eqnarray}
&5.1 && 2 && 1 && 0 && 2\\
&0 && 5 && 3 && 1 && 3\\
&5 && 2 && 4 && 1 && 4\\
&0 && 4 && 3 && 0 && 5 \\
&5 && 2 && 0 && 2 && 6\\
\end{eqnarray}\right]
$$
## 1. Compute the symmetric part $\mathbf{A}_s = \frac{1}{2}\left(\mathbf{A}+\mathbf{A}^\textrm{T}\right)$
## 2. Compute the skew-symmetric part $\mathbf{A}_{ss} = \frac{1}{2}\left(\mathbf{A}-\mathbf{A}^\textrm{T}\right)$
## 3. Confirm that $\mathbf{A} = \mathbf{A}_s + \mathbf{A}_{ss}$
## 4. Given a real symmetric matrix $\mathbf{B}$ then $\mathbf{x}$ that satisfies $\max_{\mathbf{x}} \mathbf{x}^\textrm{T} \mathbf{B}\mathbf{x},\;\;s.t.\;\|\mathbf{x}\| = 1$ is the eigenvector associated with the largest eigenvalue. Solve for the largest eigenvalue. Note: $\max_x f(x)$ is equivalent to $\min_x -f(x)$
## 5. Compare your solution to the solution of np.linalg.eig
## 6. After solving for 1. modify the optimization problem to solve for the second largest eigenvalue and eigenvector.